GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNxbDIiLCJpZCI6MiwiaWF0IjoxNjk5MzQ4NjIyfQ.7QbKVw_V6xpRhpDLST1n0YbrB_oSDHHqo8c3M0B3GvE

{
    "content": "note4",
    "important": false
}

###
PUT http://localhost:3001/api/notes/5
Content-Type: application/json

{
    "important": false
}

###
DELETE http://localhost:3001/api/notes/15

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{   "username":"sql3",
    "name": "sequalize",
    "disabled":true
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"sql3",
    "password":"secret"
}