GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "new post without authentication",
    "important": true
}

###
PUT http://localhost:3001/api/notes/5
Content-Type: application/json

{
    "important": false
}

###
DELETE http://localhost:3001/api/notes/15

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{   "username":"pratiksha",
    "name": "pratiksha"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username":"niru",
    "password":"secret"
}