GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
   
    "title":"use of express-async-errors",
    "author":"sequel",
    "url": "http://sql.com",
    "likes": 5
    
}

###
DELETE  http://localhost:3003/api/blogs/3

###
PUT http://localhost:3003/api/blogs/27
Content-Type: application/json

{
    "likes": 3
}

###
GET http://localhost:3003/api/users/

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username":"datatime",
    "name": "sql"
    
}

###
PUT http://localhost:3003/api/users/datatime
Content-Type: application/json

{
    "username":"szl"

}
