GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyQGdtYWlsLmNvbSIsImlkIjoyLCJpYXQiOjE2OTk2MDM2Mjh9.TuWiaw-zuhNKS0XoJbUAojru0Ohn2N0aRHyYbZH3uGo

{
   
    "title":"second blog using user2",
    "author":"user2",
    "url": "http://sql.com",
    "likes": 25
    
}

###
DELETE  http://localhost:3003/api/blogs/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyQGdtYWlsLmNvbSIsImlkIjoyLCJpYXQiOjE2OTk2MDM0NTF9.IsuzsaJCfZuPs61AzJPslVubZ90KHwlWQ29lFzIPSpk

###
PUT http://localhost:3003/api/blogs/27
Content-Type: application/json

{
    "likes": 3
}

###
GET http://localhost:3003/api/users/

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
   "username":"user2@gmail.com",
   "name":"user2",
   "password":"123"
}

###
PUT http://localhost:3003/api/users/user4@gmail.com
Content-Type: application/json

{
    "username":"user"

}

###
POST http://localhost:3003/api/login/
Content-Type: application/json

{
    "username":"user2@gmail.com",
    "password":"123"

}
