GET http://localhost:3003/api/blogs/3

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "blog in relation database 3",
    "author": "sequal",
    "url": "http://sql.com"
    
}

###
DELETE  http://localhost:3003/api/blogs/3
